import json
from pathlib import Path
from typing import Any, Dict
import logging

from translator_model import indic_translator

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

DATASET_DIR = Path(__file__).parent / "dataset"
DATASET_FILES = {
    "Santali": "santali.json",
    "Ho": "ho.json",
    "Mundari": "mundari.json",
}

# Language name to IndicTrans2 tag mapping
LANG_MAP = {
    "Hindi": "hin_Deva",
    "Santali": "sat_Olck",
    "Mundari": "unr_Deva",
    "Ho": "hoc_Deva"  # Note: Ho is not in the official 320M model tags
}

def _is_dataset_record(value: Any) -> bool:
    return (
        isinstance(value, dict)
        and isinstance(value.get("hindi"), str)
        and isinstance(value.get("translation"), str)
        and isinstance(value.get("phonetic"), str)
    )

def load_dataset(language: str) -> list[dict[str, str]]:
    filename = DATASET_FILES.get(language)
    if not filename:
        return []

    file_path = DATASET_DIR / filename
    if not file_path.exists():
        return []

    try:
        with open(file_path, "r", encoding="utf-8") as file:
            data = json.load(file)
    except (json.JSONDecodeError, OSError):
        return []

    if not isinstance(data, list):
        return []

    return [record for record in data if _is_dataset_record(record)]

def translate_text(text: str, source_lang_name: str, target_lang_name: str) -> dict[str, Any]:
    """
    Translates text by first checking the verified dictionary,
    then falling back to the ML model for supported pairs.
    """
    text_clean = text.strip()
    text_lower = text_clean.lower()

    src_tag = LANG_MAP.get(source_lang_name)
    tgt_tag = LANG_MAP.get(target_lang_name)

    logger.info(f"Translation Request: '{text_clean}' ({source_lang_name} -> {target_lang_name})")

    # 1. Dictionary Lookup (Only if one of the languages is Hindi)
    if source_lang_name == "Hindi" or target_lang_name == "Hindi":
        vernacular_lang = target_lang_name if source_lang_name == "Hindi" else source_lang_name
        data = load_dataset(vernacular_lang)

        for item in data:
            hindi_val = item.get("hindi", "").strip().lower()
            vernacular_val = item.get("translation", "").strip().lower()

            # Hindi -> vernacular
            if source_lang_name == "Hindi" and hindi_val == text_lower:
                logger.info(f"Dictionary match found (Hindi->{vernacular_lang})")
                return {
                    "translation": item.get("translation", ""),
                    "phonetic": item.get("phonetic", ""),
                    "offline": True,
                    "found": True,
                    "message": "Translation found in dictionary"
                }
            # vernacular -> Hindi
            elif target_lang_name == "Hindi" and vernacular_val == text_lower:
                logger.info(f"Dictionary match found ({vernacular_lang}->Hindi)")
                return {
                    "translation": item.get("hindi", ""),
                    "phonetic": "",
                    "offline": True,
                    "found": True,
                    "message": "Translation found in dictionary"
                }

    # 2. ML Model Fallback (Supported Pairs Only)
    # Check if BOTH language tags are supported by the model
    # (Verified tags in previous step: hin_Deva, sat_Olck, unr_Deva)
    supported_tags = {"hin_Deva", "sat_Olck", "unr_Deva"}

    if src_tag in supported_tags and tgt_tag in supported_tags:
        logger.info(f"Calling ML Model: {src_tag} -> {tgt_tag}")
        try:
            translation = indic_translator.translate(text_clean, src_tag, tgt_tag)
            if translation:
                return {
                    "translation": translation,
                    "phonetic": "",
                    "offline": False,
                    "found": True,
                    "message": "Translation generated by ML model"
                }
        except Exception as e:
            logger.error(f"Model inference failed: {e}")

    # 3. Handle Unsupported Ho
    if source_lang_name == "Ho" or target_lang_name == "Ho":
        return {
            "translation": "",
            "phonetic": "",
            "offline": False,
            "found": False,
            "message": "Ho translation is not currently supported by the installed model."
        }

    # 4. Final Fallback
    return {
        "translation": "",
        "phonetic": "",
        "offline": False,
        "found": False,
        "message": "Translation not found or unsupported language pair."
    }
